### ISSUE TITLE
Issue with switching between Stable and Milestone on download page

### ISSUE THREAD

**Issue by jimoquinn** [NaomiProject/naomi-website#21]
When switching between Stable and Milestone on the download page (https://projectnaomi.com/download/) the version in step #4 in the Manual Installation section isn't changing.  It should switch between "cd Naomi-2.2" and "cd Naomi-3.0.M2".

**Comment by AustinCasteel** [comment]
Fixed it with [PR #22](https://github.com/NaomiProject/naomi-website/pull/22). I got step 2 & 3 back setup and working at the end of January when milestone one came out but I must of over looked step 4 since then. Thanks for catching it!

**Comment by redragonx** [comment]
Closing this as it was fixed in PR #22
