### ISSUE TITLE
Naobian Download missing?

### ISSUE THREAD

**Issue by Teku16** [NaomiProject/naomi-website#35]
## Description

When I go to download Naobian the link to v1.0 404's

## Expected Behavior

I should download the Naobian img.

## Actual Behavior

It just 404's

## Possible Fix

Reupload?

## Steps to Reproduce

1. https://projectnaomi.com/download/
2. Click download
3. ???
4. Profit

**Comment by AustinCasteel** [comment]
I apologize for the inconvenience. During the last migration over to Netlify, which provides continuous deployment and hosting for our website, the Naobian img was neglected. The issue has been resolved and thank you for letting us know about it!

If you have any questions, comments, or concerns with Naomi; you can join our [discord](https://discord.gg/knequ9t) where you can interact with the devs and other users.
